name: plant_care
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  getwidget: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter_custom_clippers: ^2.1.0
  dots_indicator: ^3.0.0
  firebase_auth: ^4.9.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2
  flutter:
    sdk: flutter
  flutter_calendar_carousel: ^2.4.2
  dartz: ^0.10.1
  font_awesome_flutter: ^10.5.0



dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
